steps:
  - read: package_name
    prompt: "What is the name of the package?"
    default:
      from: git.remote_name
      fallback:
        from: filesystem.rootdir

  - read: package_description
    prompt: "Describe the package in a sentence."
  
  - read: package_author
    prompt: "Who is the author of the package?"
    default:
      from: git.author_name

  - read: repo_host
    from: git.remote_provider

  - read: repo_owner
    from: git.remote_owner

  - read: repo_name
    from: git.remote_name

  - read: repo_url
    eval: 'https://{{ repo_host }}/{{ repo_owner }}/{{ repo_name }}'

  - read: issues_url
    eval: '{{ repo_url }}/issues'

  - read: homepage_url
    prompt: "What is the project home page?"
    default: '{{ repo_url }}#readme'

  - read: clone_url
    prompt: "Where can people clone the project from?"
    default:
      from: git.remote_url

  - use: trcps/npm-autopublish
    with:
      test_command: npm run coverage
      lint_command: npm run lint

  - copy: README.md.tmpl
    to: README.md
  - remove: node_modules
  - update: '**/*.ts'
  - update: package.json
  - copy: workflows/**/*
    to: .github/workflows
  - remove: workflows

  - use: trcps/license
    with:
      owner: '{{ package_author }}'
      project_name: '{{ package_name }}'
      project_url: '{{ homepage_url }}'

  - remove: '**/*.tmpl'
    include hidden: true

  - remove: .tmplr.yml
